import Image from "next/image";
import scouts from "../../public/leadership/Scouts.jpg"
import cope from "../../public/leadership/COPE.jpg"
import oa from "../../public/leadership/OA.jpg"

export default function Leadership() {
  return (
  <main>
    <h1>Leadership</h1>
    <p>Leadership has defined the way I perceive the world, it has influenced my goals, and it has defined who I am in every subtle and unsubtle way. When I reflect on my own life, I am constantly reminded of the mentors and the leaders who have made their impact on me. I am also reminded of the steps I have taken to not follow in the wrong footsteps as well.</p>
    <p>Leadership feels like a daunting aspect of our lives where it almost feels undefinable; yet when we see it, we can immediately recognize it. It exists in the people who right the ship when we go off course, or those who fix the situation after everything has gone wrong. Even after dedicating my college degree to management and leadership, I still feel like there is always more to learn.</p>
    <p>I hope in this, you will understand why leadership has become such a fundamental interest of mine. It is in every small interaction and decision. It is what influences those around you and changes their behavior for good or for bad. As humans, we have live in this idea and practice it in every waking moment.</p>
    <h3>Youth and the Cub Scouts</h3>
    <p> Like most people, I started Cub Scouts not because I wanted to but because I had to. I joined the Tiger den a year too early as my brother joined his friends in the Bear den; my twin brother and I slipped through as our father was friends with pack leader. As time went on our father became the pack leader and our baseball coach and then the youth little league president.</p>
    <p>I did not recognize it then, but he had an impact on not only his own kids but almost every other kid in our town. He stepped up and organized meetings, baseball schedules, practices, campouts, the pinewood derby, etc. There was not an event where he did not help plan it. His leadership and management skills made my childhood so much more enjoyable and memorable.</p>
    <h3>The Boy Scouts</h3>
    <p>It was not until I was around eleven and joined Boy Scouts that I got my first glimpse of what youth leadership meant. For the most part, it looked like one person doing everything: planning meetings, organizing campouts, and managing patrols on their own. That began to change when I was elected Senior Patrol Leader at fifteen. The role made me realize that leadership is genuinely hard, and that it is deceptively “easier” to simply do things yourself than to delegate and trust others. Positions like SPL often went nearly uncontested; they knew it was a lot of work, but no true leaders had shown anyone how it is supposed to be done.</p>
    <p>Halfway through my tenure, a new Scoutmaster was appointed. Before our state jamboree, he told me to "keep my hands in my pockets" and would remind me every time I tried to finish a task myself. I resented the advice in the moment: we fell behind schedule, I had to track people down, and work was getting done sloppily. But in hindsight, it was one of the best rules he could have given me. He forced me to delegate, to share responsibility, convince others to do a task a certain way; this simple rule forced me to learn some real leadership skills.</p>
    <div style={{ position: "relative", width: "100%", aspectRatio: "16/9" }}>
      <Image src={scouts} alt="Scouting Photo" fill style={{ objectFit: "cover", borderRadius: "0.75rem" }} />
    </div>
    <h3>Camp Counselor and Climbing Instructor</h3>
    <p>It was only after earning Eagle Scout that I began to excel at practicing my leadership. I found my stride toward the end of my second summer as a counselor, but it truly clicked in my third. That year I was assigned the ten and eleven year-olds; this group, left unchecked, can be among the most chaotic at any camp. What saved me was discovering C.O.P.E. (Challenging Outdoor Personal Experience). While other counselors gave their campers free time in the mornings, I ran structured activities alongside mine. They connected with me because they could see I was invested in the activities and them. By the end of the summer, we had built a cohesive enough group to construct a Roman-style standard together. To my leadership, we were the standout group at the campfire.</p>
    <p>Over the following fall, winter, and spring, I began working with the climbing staff at camp, running weekend programming for troops and visiting groups. This is where I started to understand what it truly means to teach and guide. Explaining and demonstrating a skill is straightforward; enabling someone else to internalize and use it is something else entirely. C.O.P.E. gave me a framework for that; it is built around soft leadership skills like trust, group dynamics, and, most importantly, how to fail productively. Treating every failure as a learning opportunity sounds obvious, but it is genuinely difficult in practice. The instinct is to get frustrated, deflect blame, or reach for an excuse. Learning to do the opposite is what separates good leaders from great ones.</p>
    <p>I was also fortunate to be surrounded by other instructors who wanted to pass those same values on to me. They gave me a platform to experiment, take ownership, and build a vision. At my first instructor course, I was asked to teach adults (people two and three times my age) how to tie knots, inspect gear, and follow standard operating procedures. Standing up in front of that room at sixteen was daunting, but it taught me something I have never forgotten: everyone has a voice worth hearing, and everyone deserves a chance to be heard.</p>
    <div style={{ position: "relative", width: "100%", aspectRatio: "16/9" }}>
      <Image src={cope} alt="COPE Photo" fill style={{ objectFit: "cover", borderRadius: "0.75rem" }} />
    </div>
    <h3>Formal Leadership Education and Outdoor Adventures</h3>
    <p>I joined Outdoor Adventures the day I arrived at Boston College. I walked straight to the office and asked the director for a job. She hired me almost immediately as she needed the help, and through that program I met some of the best people I know. It was my first real community; it was something people had built with genuine care, and something I was fully bought into from the start.</p>
    <p>At the beginning of my sophomore year, our lead route setter stepped down. I had only been setting for a year, but my climbing background gave me the confidence to step up. I was also the only returning route setter, which was both nerve wracking and, in retrospect, a gift. It meant I got to build the team from scratch; I got to teach everything I knew and shaped the culture around safety and continuous self-improvement.</p>
    <p>At the same time, I was taking my first formal leadership courses. I was introduced to concepts like psychological safety, emotional intelligence, and influence tactics, and I had a live environment in which to practice all of them. Through that process I developed my leadership style deliberately: servant leadership, in the tradition of Pope Francis. That choice was not arbitrary. It grew directly from my Jesuit education at BC High and the habit of reflection that both the scouts and that school had instilled in me over the years.</p>
    <div style={{ position: "relative", width: "100%", aspectRatio: "16/9" }}>
      <Image src={oa} alt="OA Photo" fill style={{ objectFit: "cover", borderRadius: "0.75rem" }} />
    </div>
    <h3>So What?</h3>
    <p>After one particularly stressful route-setting session, we sat down for our weekly debrief. One of the members began to voice his frustrations. The rest of us listened, responded honestly but kindly, and adjusted how we worked together. That small moment means more to me than almost anything else from that time. It started a pattern: we learned to give and receive criticism with respect, and to push each other's work without damaging each other's confidence. We had become a real team; a team where everyone brought their best because we had built the trust to be honest with one another.</p>
    <p>Leadership has shaped how I approach everything. It has taught me to look at any system (any team, any process, any room I walk into) and ask where I can make it better, not just for myself but for everyone in it. Existing within a system has never felt like enough. I want to improve it.</p>
    <br></br>
    <p>There have been so many great leaders in my life, and I cannot thank them enough. They have helped make me who I am today, and so I want to end by thanking them: Chuck Blanchette, Nick Kerpan, Dave Humphreys, Ron Gauld, Karl DeBisschop, Mike Jones, John Iler, Stephanie MacFarland, Ricky Savage, Allison Batey, Gabby Munger, and Frances Steelquist.</p>
  </main>
);
}
